// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGvNdnZkI9XIEBgxvaGkUlZQERwompnA',
    appId: '1:884390625587:web:09eee70cd2a61dd58dbe46',
    messagingSenderId: '884390625587',
    projectId: 'nub-student-association',
    authDomain: 'nub-student-association.firebaseapp.com',
    storageBucket: 'nub-student-association.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZdMiupVEkVYGuT11wh9yxZPdU5rpqv8',
    appId: '1:884390625587:android:8bfd8026a1657f2f8dbe46',
    messagingSenderId: '884390625587',
    projectId: 'nub-student-association',
    storageBucket: 'nub-student-association.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmyti4dgalWXQjABoBkGd-M3jEJaXdkqU',
    appId: '1:884390625587:ios:ce0b071bcabc5cf28dbe46',
    messagingSenderId: '884390625587',
    projectId: 'nub-student-association',
    storageBucket: 'nub-student-association.appspot.com',
    iosBundleId: 'com.nub.studentAssociation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmyti4dgalWXQjABoBkGd-M3jEJaXdkqU',
    appId: '1:884390625587:ios:d9643d72f6af36768dbe46',
    messagingSenderId: '884390625587',
    projectId: 'nub-student-association',
    storageBucket: 'nub-student-association.appspot.com',
    iosBundleId: 'com.nub.studentAssociation.RunnerTests',
  );
}
