// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKhV2I807TzSI-RymNVE3euVB9PK_1RU',
    appId: '1:940829537826:web:314b2369e15ee5144cfc7b',
    messagingSenderId: '940829537826',
    projectId: 'six-teen',
    authDomain: 'six-teen.firebaseapp.com',
    storageBucket: 'six-teen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjIoxEJ5XDcB7TK6B-9vytSD_jHLok8Q',
    appId: '1:940829537826:android:10118ed1b4b639594cfc7b',
    messagingSenderId: '940829537826',
    projectId: 'six-teen',
    storageBucket: 'six-teen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xSKFX88eJx39IWZauubS-wpqmB0jWGI',
    appId: '1:940829537826:ios:0cbe3fd15472e6484cfc7b',
    messagingSenderId: '940829537826',
    projectId: 'six-teen',
    storageBucket: 'six-teen.appspot.com',
    iosBundleId: 'com.sixteen.user.sixteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xSKFX88eJx39IWZauubS-wpqmB0jWGI',
    appId: '1:940829537826:ios:4cf8db4812314c864cfc7b',
    messagingSenderId: '940829537826',
    projectId: 'six-teen',
    storageBucket: 'six-teen.appspot.com',
    iosBundleId: 'com.sixteen.user.sixteen.RunnerTests',
  );
}
